"""思科 Cisco IOS 命令生成器。

Cisco IOS 语法特色：
- 使用 wildcard mask（反掩码）对标 subnet mask
- ACL 使用 access-list 编号
- VLAN 用 name 代替 description
- EtherChannel 用 channel-group
- STP 用 spanning-tree mode rapid-pvst
"""
from __future__ import annotations

from typing import Any, Dict, List


class CiscoConfigGenerator:
    """Cisco IOS 交换机/路由器配置生成器"""

    @staticmethod
    def generate_header(config: Dict[str, Any]) -> str:
        """生成配置头部"""
        lines = ["!", f"! Cisco IOS Configuration"]
        if config.get("hostname"):
            lines.append(f"! Hostname: {config['hostname']}")
        lines.extend(["!", f"! Generated by NetCmdGen", "!"])
        return "\n".join(lines)

    # ═══════════════════════════════════════════════════════
    # Basic 基础配置
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_basic_config(params: Dict[str, Any]) -> str:
        """生成基础配置（主机名/SSH/Telnet/NTP/SNMP/用户）。"""
        out: List[str] = ["!", "# 基础配置", "!"]
        out.append("configure terminal")

        if params.get("hostname"):
            out.append(f"hostname {params['hostname']}")

        if params.get("enable_secret"):
            out.append(f"enable secret {params['enable_secret']}")
        elif params.get("password"):
            p = params["password"]
            val = p.get("value", "admin123")
            if p.get("encrypted"):
                out.append(f"enable secret 5 {val}")
            else:
                out.append(f"enable secret {val}")

        # SSH 配置
        if params.get("enable_ssh"):
            ssh = params.get("ssh", {})
            domain = params.get("domain_name", "local")
            out.extend([
                f"ip domain-name {domain}",
                "crypto key generate rsa modulus 2048",
                f"ip ssh version 2",
                f"ip ssh time-out {ssh.get('timeout', 60)}",
                f"ip ssh authentication-retries {ssh.get('max_auth_tries', 3)}",
            ])

        # Telnet/SSH 线路配置
        if params.get("enable_ssh") or params.get("enable_telnet"):
            out.extend([
                "line vty 0 4",
                " login local",
            ])
            if params.get("enable_telnet"):
                out.append(" transport input telnet ssh")
            else:
                out.append(" transport input ssh")
            out.append("!")

        # 用户
        if params.get("user"):
            u = params["user"]
            username = u.get("username", "admin")
            password = u.get("password", "admin123")
            level = u.get("level", 15)
            encrypted = "5 " if u.get("encrypted") else ""
            out.append(f"username {username} privilege {level} secret {encrypted}{password}")

        # NTP
        if params.get("ntp"):
            ntp = params["ntp"]
            servers = ntp.get("servers", ["202.120.2.101"])
            tz = ntp.get("timezone", "UTC+8")
            if isinstance(servers, list):
                for s in servers:
                    out.append(f"ntp server {s}")
            out.append(f"clock timezone {tz} 8")

        # SNMP
        if params.get("snmp"):
            s = params["snmp"]
            ro = s.get("community_read", "public")
            out.append(f"snmp-server community {ro} RO")
            if s.get("community_write"):
                out.append(f"snmp-server community {s['community_write']} RW")
            if s.get("sys_location"):
                out.append(f"snmp-server location {s['sys_location']}")
            if s.get("sys_contact"):
                out.append(f"snmp-server contact {s['sys_contact']}")
            if s.get("trap_host"):
                out.append(f"snmp-server host {s['trap_host']} version 2c {ro}")

        # 日志
        if params.get("log"):
            log = params["log"]
            out.append("logging buffered 4096 informational")
            if log.get("host"):
                out.append(f"logging host {log['host']}")

        if len(out) <= 4:
            return ""
        return "\n".join(out)

    # ═══════════════════════════════════════════════════════
    # VLAN 配置
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_vlan_config(params: Dict[str, Any]) -> str:
        """生成 VLAN 配置。"""
        out: List[str] = ["!", "# VLAN 配置", "!"]

        if params.get("vlans"):
            for vlan in params["vlans"]:
                vid = vlan.get("id", vlan.get("vlan_id", ""))
                name = vlan.get("name", f"VLAN{vid}")
                out.append(f"vlan {vid}")
                out.append(f" name {name}")
                out.append("!")

        # 接口 VLAN 分配
        if params.get("interfaces"):
            out.append("")
            for iface in params["interfaces"]:
                port = iface.get("interface", "")
                access_vlan = iface.get("vlan_id") or iface.get("access_vlan")
                trunk_vlans = iface.get("trunk_vlans") or iface.get("allowed_vlans")
                pvid = iface.get("pvid") or iface.get("native_vlan")

                out.append(f"interface {port}")
                link_type = iface.get("type", iface.get("linkType", "access"))
                if link_type == "trunk":
                    out.append(" switchport mode trunk")
                    if trunk_vlans:
                        vlans = trunk_vlans if isinstance(trunk_vlans, str) else ",".join(str(v) for v in trunk_vlans)
                        out.append(f" switchport trunk allowed vlan {vlans}")
                    if pvid:
                        out.append(f" switchport trunk native vlan {pvid}")
                else:
                    out.append(" switchport mode access")
                    if access_vlan:
                        out.append(f" switchport access vlan {access_vlan}")
                out.append("!")

        # VLANIF / SVI
        if params.get("vlanifs"):
            out.append("")
            for vf in params["vlanifs"]:
                out.extend([
                    f"interface vlan {vf['vlan_id']}",
                    f" ip address {vf['ip_address']} {vf.get('mask', '255.255.255.0')}",
                    " no shutdown",
                ])
                if vf.get("description"):
                    out.append(f" description {vf['description']}")
                out.append("!")

        return "\n".join(out)

    # ═══════════════════════════════════════════════════════
    # Routing 路由配置
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_routing_config(params: Dict[str, Any]) -> str:
        """生成路由配置（静态路由 / OSPF / BGP / EIGRP）。"""
        out: List[str] = ["!", "# 路由配置", "!"]
        out.append("ip routing")

        # 静态路由
        if params.get("static_routes"):
            for r in params["static_routes"]:
                dest = r.get("dest", r.get("network", ""))
                mask = r.get("mask", "255.255.255.0")
                nh = r.get("nexthop", r.get("gateway", ""))
                out.append(f"ip route {dest} {mask} {nh}")

        # 默认路由
        if params.get("default_route"):
            dr = params["default_route"]
            out.append(f"ip route 0.0.0.0 0.0.0.0 {dr.get('nexthop', dr.get('gateway', ''))}")

        # OSPF
        if params.get("ospf"):
            ospf = params["ospf"]
            pid = ospf.get("process_id", 1)
            rid = ospf.get("router_id", "")
            out.extend([f"router ospf {pid}"])
            if rid:
                out.append(f" router-id {rid}")
            for net in ospf.get("networks", []):
                network = net.get("network", "")
                wildcard = net.get("wildcard", "0.0.0.255")
                area = net.get("area", "0")
                out.append(f" network {network} {wildcard} area {area}")
            out.append("!")

        # BGP
        if params.get("bgp"):
            bgp = params["bgp"]
            asn = bgp.get("as_number", 65001)
            rid = bgp.get("router_id", "")
            out.extend([f"router bgp {asn}"])
            if rid:
                out.append(f" bgp router-id {rid}")
            for peer in bgp.get("peers", []):
                out.append(f" neighbor {peer.get('ip', '')} remote-as {peer.get('asn', peer.get('remote_as', 65001))}")
            for net in bgp.get("networks", []):
                network = net.get("network", "")
                mask = net.get("mask", "255.255.255.0")
                out.append(f" network {network} mask {mask}")
            out.append("!")

        # EIGRP (思科特有)
        if params.get("eigrp"):
            eigrp = params["eigrp"]
            asn = eigrp.get("as_number", 100)
            out.extend([f"router eigrp {asn}"])
            if eigrp.get("router_id"):
                out.append(f" eigrp router-id {eigrp['router_id']}")
            out.append(" no auto-summary")
            for net in eigrp.get("networks", []):
                out.append(f" network {net.get('network', '')} {net.get('wildcard', '0.0.0.255')}")
            out.append("!")

        return "\n".join(out)

    # ═══════════════════════════════════════════════════════
    # Security 安全配置
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_security_config(params: Dict[str, Any]) -> str:
        """生成安全配置（ACL / 端口安全 / STP / DHCP Snooping）。"""
        out: List[str] = ["!", "# 安全配置", "!"]

        # ACL
        if params.get("acls"):
            for acl in params["acls"]:
                num = acl.get("number", acl.get("name", 100))
                out.append(f"! ACL {num}")
                for rule in acl.get("rules", []):
                    action = rule.get("action", "permit")
                    proto = rule.get("protocol", "ip")
                    src = rule.get("source", rule.get("sourceIp", "any"))
                    dst = rule.get("destination", rule.get("destIp", "any"))
                    # Cisco uses wildcard mask format
                    if src != "any":
                        out.append(f"access-list {num} {action} {proto} {src} {dst}")
                    else:
                        out.append(f"access-list {num} {action} {proto} any any")
                out.append("!")

        # 端口安全
        if params.get("port_security"):
            for ps in params["port_security"]:
                out.extend([
                    f"interface {ps['interface']}",
                    " switchport port-security",
                    f" switchport port-security maximum {ps.get('max_mac', 1)}",
                    f" switchport port-security violation {ps.get('violation', 'shutdown')}",
                ])
                if ps.get("sticky"):
                    out.append(" switchport port-security mac-address sticky")
                out.append("!")

        # STP
        if params.get("stp"):
            stp = params["stp"]
            mode = stp.get("mode", "rapid-pvst")
            out.extend([
                f"spanning-tree mode {mode}",
                f"spanning-tree vlan 1 priority {stp.get('priority', 32768)}",
            ])
            if stp.get("bpduguard"):
                out.extend(["spanning-tree portfast bpduguard default", "!"])
            else:
                out.append("!")

        # DHCP Snooping
        if params.get("dhcp_snooping"):
            ds = params["dhcp_snooping"]
            if ds.get("enable", True):
                out.extend(["ip dhcp snooping"])
                for v in ds.get("vlans", ds.get("trusted_vlans", [])):
                    out.append(f"ip dhcp snooping vlan {v}")
                for port in ds.get("trusted_ports", []):
                    out.extend([f"interface {port}", " ip dhcp snooping trust", "!"])
                out.append("!")

        # DAI 动态 ARP 检测
        if params.get("arp_inspection"):
            ai = params["arp_inspection"]
            out.append("! DAI 动态ARP检测")
            for v in (ai.get("vlans") or []): out.append(f"ip arp inspection vlan {v}")
            for port in (ai.get("trusted_ports") or []):
                out.extend([f"interface {port}", " ip arp inspection trust", "!"])

        # IP Source Guard
        if params.get("ip_source_guard"):
            isg = params["ip_source_guard"]
            out.append("! IP Source Guard")
            for port in (isg.get("ports") or []):
                out.extend([f"interface {port}", " ip verify source", "!"])

        # 风暴控制
        if params.get("storm_control"):
            sc = params["storm_control"]
            out.append("! 风暴控制")
            for port in (sc.get("ports") or []):
                out.extend([
                    f"interface {port}",
                    f" storm-control broadcast level {sc.get('broadcast_pct',50)}",
                    f" storm-control multicast level {sc.get('multicast_pct',50)}",
                    f" storm-control unicast level {sc.get('unicast_pct',80)}",
                    f"!",
                ])

        # Private VLAN (思科特有)
        if params.get("private_vlan"):
            pv = params["private_vlan"]
            out.append("! Private VLAN")
            out.append(f"vlan {pv.get('primary',100)}")
            out.append(" private-vlan primary")
            out.append(f"vlan {pv.get('community',101)}")
            out.append(" private-vlan community")
            out.append(f"vlan {pv.get('isolated',102)}")
            out.append(" private-vlan isolated")
            out.append("!")

        return "\n".join(out)

    # ═══════════════════════════════════════════════════════
    # Interface 接口配置
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_interface_config(params: Dict[str, Any]) -> str:
        """生成接口配置（EtherChannel / LLDP / PoE / 限速）。"""
        out: List[str] = ["!", "# 接口配置", "!"]

        # EtherChannel (思科特有命名)
        if params.get("eth_trunks"):
            for trunk in params["eth_trunks"]:
                tid = trunk.get("trunk_id", 1)
                mode = trunk.get("mode", "lacp")
                proto = "lacp" if mode == "lacp" else "pagp"
                out.append(f"! EtherChannel Po{tid}")
                for member in (trunk.get("members") or []):
                    out.extend([
                        f"interface {member}",
                        f" channel-group {tid} mode active",
                        "!" if proto == "lacp" else f" channel-group {tid} mode desirable",
                        "!" if proto == "lacp" else "",
                    ])
                if proto == "lacp":
                    out.append("")
                out.extend([
                    f"interface port-channel {tid}",
                    " switchport mode trunk",
                ])
                if trunk.get("description"):
                    out.append(f" description {trunk['description']}")
                out.append("!")

        # LLDP
        if params.get("lldp"):
            lldp = params["lldp"]
            if lldp.get("enable", True):
                out.extend(["lldp run"])
                if lldp.get("timer"):
                    out.append(f"lldp timer {lldp['timer']}")
                if lldp.get("holdtime"):
                    out.append(f"lldp holdtime {lldp['holdtime']}")
                out.append("!")

        # PoE
        if params.get("poe_interfaces"):
            for poe in params["poe_interfaces"]:
                iface = poe.get("interface") or poe.get("port", "")
                if not iface:
                    continue
                out.extend([f"interface {iface}"])
                if poe.get("enable", True):
                    out.append(" power inline auto")
                if poe.get("max_power"):
                    out.append(f" power inline consumption {poe['max_power']}")
                out.append("!")

        return "\n".join(out)

    # ═══════════════════════════════════════════════════════
    # WAN 上网配置（路由器专属）
    # ═══════════════════════════════════════════════════════

    # ═══════════════════════════════════════════════════════
    # IPv6 配置
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_ipv6_config(params: Dict[str, Any]) -> str:
        """生成 IPv6 基础配置（全局启用 + 接口地址 + RA 通告）。"""
        out: List[str] = ["!", "# IPv6 配置", "!"]
        out.append("ipv6 unicast-routing")
        for iface in (params.get("interfaces") or []):
            port = iface.get("interface", "GigabitEthernet0/1")
            addr = iface.get("ipv6_address", "")
            if addr:
                out.extend([
                    f"interface {port}",
                    " ipv6 enable",
                    f" ipv6 address {addr}",
                ])
                if iface.get("ipv6_ra", True):
                    out.append(" ipv6 nd ra-interval 30")
                    out.append(" ipv6 nd ra-lifetime 1800")
                # 无状态自动配置
                if iface.get("ipv6_autoconfig"):
                    out.append(" ipv6 nd other-config-flag")
                out.append("!")
        # IPv6 静态路由
        for r in (params.get("ipv6_routes") or []):
            out.append(f"ipv6 route {r.get('dest','::/0')} {r.get('nexthop','')}")
        return "\n".join(out)

    @staticmethod
    def generate_wan_config(params: Dict[str, Any]) -> str:
        """生成 WAN 口上网配置（PPPoE / 静态IP / DHCP Client）。"""
        out: List[str] = ["!", "# WAN 广域网配置", "!"]
        wan_type = params.get("connectionType", "static")
        iface = params.get("interface", "GigabitEthernet0/0")

        out.append(f"interface {iface}")
        out.append(f" description WAN-{wan_type.upper()}")

        if wan_type == "pppoe":
            out.extend([
                " pppoe enable",
                " pppoe-client dial-pool-number 1",
                " no shutdown",
                "!",
                "interface Dialer 1",
                " ip address negotiated",
                " encapsulation ppp",
                " dialer pool 1",
                f" dialer-group 1",
                " ppp authentication chap pap callin",
                f" ppp chap hostname {params.get('pppoeUser', '')}",
                f" ppp chap password 0 {params.get('pppoePassword', '')}",
                " no shutdown",
                "!",
                "dialer-list 1 protocol ip permit",
            ])
        elif wan_type == "dhcp":
            out.extend([" ip address dhcp", " no shutdown"])
        else:
            out.extend([
                f" ip address {params.get('wanIp', '')} {params.get('wanMask', '255.255.255.0')}",
                " no shutdown",
            ])
            if params.get("wanGateway"):
                out.append(f"!ip route 0.0.0.0 0.0.0.0 {params['wanGateway']}")

        out.append("!")
        return "\n".join(out)

    # ═══════════════════════════════════════════════════════
    # DHCP 服务
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_dhcp_config(params: Dict[str, Any]) -> str:
        """生成 DHCP 服务配置。"""
        out: List[str] = ["!", "# DHCP 服务", "!"]
        out.append("service dhcp")
        for line in (params.get("dhcpLines") or params.get("lines") or []):
            net = line.get("network", "")
            mask = line.get("mask", "255.255.255.0")
            gw = line.get("gateway", "")
            dns = line.get("dns", "")
            start_ip = line.get("startIp", "") or line.get("start_ip", "")
            end_ip = line.get("endIp", "") or line.get("end_ip", "")
            pool_name = f"DHCP-{net.split('.')[2] if net else 'LAN'}"
            out.extend([
                f"ip dhcp pool {pool_name}",
                f" network {net} {mask}",
            ])
            if gw:
                out.append(f" default-router {gw}")
            if dns:
                out.append(f" dns-server {dns}")
            if start_ip and end_ip:
                out.append(f" range {start_ip} {end_ip}")
            out.append(f" lease {line.get('lease', '1')}")
            out.append("!")

        # 排除地址
        for line in (params.get("dhcpLines") or params.get("lines") or []):
            for exclude in (line.get("excludes") or []):
                out.append(f"ip dhcp excluded-address {exclude}")
        return "\n".join(out)

    # ═══════════════════════════════════════════════════════
    # NAT 端口映射
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_nat_config(params: Dict[str, Any]) -> str:
        """生成 NAT 配置（静态映射 + PAT）。"""
        out: List[str] = ["!", "# NAT 配置", "!"]
        rules = params.get("rules") or params.get("natList") or params.get("natLines") or []
        wan_if = params.get("wanInterface", "GigabitEthernet0/0")
        lan_if = params.get("lanInterface", "GigabitEthernet0/1")

        out.extend([
            f"interface {wan_if}", " ip nat outside", "!",
            f"interface {lan_if}", " ip nat inside", "!",
        ])

        # PAT overload
        out.append("ip nat inside source list NAT-ACL interface GigabitEthernet0/0 overload")
        out.append("access-list 1 permit any")

        # 端口映射
        for r in rules:
            proto = r.get("protocol", "tcp")
            ext_port = r.get("dstPort") or r.get("externalPort") or r.get("ext_port", "")
            int_ip = r.get("toAddress") or r.get("internalIp") or r.get("int_ip", "")
            int_port = r.get("toPorts") or r.get("internalPort") or r.get("int_port", "")
            comment = r.get("comment", "")
            out.append(f"! {comment}")
            out.append(f"ip nat inside source static {proto} {int_ip} {int_port} interface {wan_if} {ext_port}")
        out.append("!")
        return "\n".join(out)

    # ═══════════════════════════════════════════════════════
    # 统一入口
    # ═══════════════════════════════════════════════════════

    @staticmethod
    def generate_ipsec_config(params: Dict[str, Any]) -> str:
        """生成 IPSec VPN 配置（IKEv1 + 预共享密钥 + transform-set + crypto map）"""
        out = ["!", "# IPSec VPN", "!"]
        ike = params.get("ike", {})
        out.extend([
            f"crypto isakmp policy 10",
            f" encr aes 256",
            f" authentication pre-share",
            f" group 14",
            f" lifetime 86400",
            f"crypto isakmp key {params.get('pre_shared_key','vpn-key')} address {params.get('peer_ip','1.2.3.4')}",
            f"crypto ipsec transform-set TS esp-aes 256 esp-sha256-hmac",
            f"!",
            f"access-list 110 permit ip {params.get('local_net','192.168.1.0')} 0.0.0.255 {params.get('remote_net','192.168.2.0')} 0.0.0.255",
            f"crypto map VPN-MAP 10 ipsec-isakmp",
            f" set peer {params.get('peer_ip','1.2.3.4')}",
            f" set transform-set TS",
            f" match address 110",
            f"interface {params.get('wan_if','GigabitEthernet0/0')}",
            f" crypto map VPN-MAP",
            f"!",
        ])
        return "\n".join(out)

    _SECTION_MAP = {
        "basic": generate_basic_config, "vlan": generate_vlan_config,
        "routing": generate_routing_config, "security": generate_security_config,
        "interface": generate_interface_config, "wan": generate_wan_config,
        "dhcp": generate_dhcp_config, "nat": generate_nat_config,
        "ipv6": generate_ipv6_config, "ipsec": generate_ipsec_config,
    }

    @staticmethod
    def generate_vxlan_config(params): return f"! VXLAN\nfeature nv overlay\nnv overlay evpn\ninterface nve1\n member vni {params.get('vni',5000)}"
    @staticmethod
    def generate_gre_config(params): return f"! GRE Tunnel\ninterface Tunnel0\n ip address {params.get('tunnel_ip','10.0.0.1')} {params.get('tunnel_mask','255.255.255.0')}\n tunnel source {params.get('source','GigabitEthernet0/0')}\n tunnel destination {params.get('destination','2.2.2.2')}\n!"

    @staticmethod
    def generate_all(config: Dict[str, Any]) -> str:
        """生成完整思科设备配置。"""
        sections: List[str] = [
            CiscoConfigGenerator.generate_header(config.get("device_model") or config.get("description") or {}),
        ]

        for key, fn in CiscoConfigGenerator._SECTION_MAP.items():
            if config.get(key):
                result = fn(config[key])
                if result:
                    sections.append(result)

        sections.append("!\nend")
        return "\n".join(sections)
